services:
  - type: web
    name: llm-layout-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MODEL_PATH
        value: models/gemma-3-1b-it-Q4_K_M.gguf
